name: Cyrille's Blog
description: The journey of a Biology Researcher in tech stuffs
meta_description: "Cyrille's Blog, The journey of a Biology Researcher in tech stuffs"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 1
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: 'vetcoder'

# Details for the RSS feed generator
url:            'https://vetcoder.github.io'
author:         'Cyrille NGUETOUM'
authorTwitter:  'cyrillenguetoum'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
            author: Cyrille NGUETOUM
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
